name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        dotnet-runtime: [win-x64, win-arm64, win-x86, linux-x64, linux-arm64, osx-x64, osx-arm64]
    runs-on: ubuntu-latest
    env:
      DOTNET_ACTION_VERSION: '10.0.x'
      DOTNET_VERSION: 'net10.0'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_ACTION_VERSION }}

    - name: Build Desktop App
      uses: huguesv/dotnet-publish-upload-action@main
      with:
        working-dir: src
        project-relative-path: Woohoo.Noise.Player/Woohoo.Noise.Player.csproj
        dotnet-version: ${{ env.DOTNET_VERSION }}
        dotnet-runtime: ${{ matrix.dotnet-runtime }}
        publish-absolute-folder: ${{ github.workspace }}/src/Woohoo.Noise.Player/bin/Release/${{ env.DOTNET_VERSION }}/${{ matrix.dotnet-runtime }}/publish
        artifact-name: desktop-${{ matrix.dotnet-runtime }}
        artifact-file-name: Woohoo.Noise.Player-${{ github.event.release.tag_name }}-${{ matrix.dotnet-runtime }}
        
    - name: Build Console App
      uses: huguesv/dotnet-publish-upload-action@main
      with:
        working-dir: src
        project-relative-path: Woohoo.Noise.Player.Cli/Woohoo.Noise.Player.Cli.csproj
        dotnet-version: ${{ env.DOTNET_VERSION }}
        dotnet-runtime: ${{ matrix.dotnet-runtime }}
        publish-absolute-folder: ${{ github.workspace }}/src/Woohoo.Noise.Player.Cli/bin/Release/${{ env.DOTNET_VERSION }}/${{ matrix.dotnet-runtime }}/publish
        artifact-name: console-${{ matrix.dotnet-runtime }}
        artifact-file-name: Woohoo.Noise.Player.Cli-${{ github.event.release.tag_name }}-${{ matrix.dotnet-runtime }}

  release:
    name: Upload Release Assets
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download binaries artifacts for all runtimes
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts
        merge-multiple: true

    - name: Display downloaded artifacts
      run: ls -R release-artifacts

    - name: Upload to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release-artifacts/*
